# Generated by Django 2.0.5 on 2018-06-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowant_api', '0011_auto_20180531_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userintegration',
            name='user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='yellowantredirectstate',
            name='user',
            field=models.IntegerField(),
        ),
    ]
